search_algorithm: genetic  # Options: q_learning, genetic, ACO, 

maze_size: big  # Options: small, big

q_learning:
  n_epoch: 200
  lr: 0.001
  epsilon: 0.9
  epsilon_decay_factor: 1
  mem_size: 2000
  batch_size: 50
  gamma: 0.9
  sync_freq: 250
  min_epochs: 50

ACO:
  # Number of steps each ant can take
  max_moves: 200
  # Number of times ants are released into maze (generations)
  max_iterations: 20
  # Numbers of ants released each iteration
  ant_count: 100
  # Numbers of runs of algorithm
  max_total_iterations: 10

genetic:
  # Number of steps each creature can take
  creature_lifespan: 100
  # Numbers of creatures released each iteration
  creature_count: 20 # divisible by 10
  # Number of times creatures are released into maze (generations)
  max_iterations: 100
  # mutate 15% of the moves
  mutation_rate: 0.15
  
